[project]
name = "PQtree_rs"
description = "Faster PQ Tree library for Python"
authors = ["Parsa Bahraminejad <pbahrami@uwaterloo.ca>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
publish = "maturin publish " 
build = "maturin build"
dev = "maturin develop"
